
exclude: .*migrations\/.*
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'uat', '--branch', dev]
    -   id: no-commit-to-branch
        name: checking branch name pattern
        args: [--pattern, '^(?!(feature|fix|hotfix)\/[a-zA-Z0-9._-]+).*$']


- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      args: [--profile=black]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8


- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.19.16
  hooks:
    - id: djlint-django

- repo: https://github.com/pycqa/bandit
  rev: 1.6.2
  hooks:
    - id: bandit


- repo: https://github.com/pycqa/pylint
  rev: "v2.17.5"
  hooks:
    - id: pylint
      exclude: "[a-zA-Z]*/(migrations)/(.)*"
      additional_dependencies: [
          pylint_django,

      ]
      args: ["--fail-under=8"]
