# Generated by Django 5.0.1 on 2024-01-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='attraction',
            options={'verbose_name': 'Attraction', 'verbose_name_plural': 'Attractions'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='cancellationpolicy',
            options={'verbose_name': 'Cancellation Policy', 'verbose_name_plural': 'Cancellation Policies'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='exclusions',
            options={'verbose_name': 'Exclusions', 'verbose_name_plural': 'Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='faqanswer',
            options={'verbose_name': 'FAQAnswer', 'verbose_name_plural': 'FAQAnswers'},
        ),
        migrations.AlterModelOptions(
            name='faqquestion',
            options={'verbose_name': 'FAQQuestion', 'verbose_name_plural': 'FAQQuestions'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Guide', 'verbose_name_plural': 'Guide'},
        ),
        migrations.AlterModelOptions(
            name='hoteldetails',
            options={'verbose_name': 'Hotel Details', 'verbose_name_plural': 'Hotel Details'},
        ),
        migrations.AlterModelOptions(
            name='inclusions',
            options={'verbose_name': 'Inclusions', 'verbose_name_plural': 'Inclusions'},
        ),
        migrations.AlterModelOptions(
            name='informationactivities',
            options={'verbose_name': 'Information Activities', 'verbose_name_plural': 'Information Activities'},
        ),
        migrations.AlterModelOptions(
            name='informations',
            options={'verbose_name': 'Information', 'verbose_name_plural': 'Informations'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itinerary'},
        ),
        migrations.AlterModelOptions(
            name='itineraryday',
            options={'verbose_name': 'Itinerary Day', 'verbose_name_plural': 'Itinerary Day'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'verbose_name': 'Package Category', 'verbose_name_plural': 'Package Category'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'Pricing', 'verbose_name_plural': 'Pricing'},
        ),
        migrations.AlterModelOptions(
            name='thingstocarry',
            options={'verbose_name': 'Things To Carry', 'verbose_name_plural': 'Things To Carry'},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'verbose_name': 'Tour Category', 'verbose_name_plural': 'Tour Categories'},
        ),
        migrations.AlterModelOptions(
            name='tourtype',
            options={'verbose_name': 'Tour Type', 'verbose_name_plural': 'Tour Type'},
        ),
        migrations.AlterModelOptions(
            name='userreview',
            options={'verbose_name': 'User Review', 'verbose_name_plural': 'User Reviews'},
        ),
        migrations.AddField(
            model_name='exclusions',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exclusions',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inclusions',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inclusions',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
