# Generated by Django 5.0.1 on 2024-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tour_class',
            field=models.CharField(choices=[('private', 'Private'), ('conducting', 'Conducting')], default='private', max_length=20, verbose_name='Tour Class'),
        ),
    ]
