# Generated by Django 5.0.1 on 2024-01-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_agent_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
