# Generated by Django 5.0.1 on 2024-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_amount_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_by',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('ORDERED', 'ORDERED'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('REFUNDED REQUESTED', 'REFUNDED'), ('REFUNDED', 'REFUNDED')], max_length=50, null=True),
        ),
    ]
