# Generated by Django 5.0.1 on 2024-01-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_published_exclusions_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inclusions',
            old_name='is_published',
            new_name='is_approved',
        ),
    ]
