# Generated by Django 5.0.1 on 2024-01-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_published_inclusions_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image',
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='attraction_images/')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attracionimages', to='api.attraction')),
            ],
        ),
    ]
