# Generated by Django 5.0.1 on 2024-02-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_created_by_booking_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='check_out',
        ),
    ]
