# Generated by Django 5.0.1 on 2024-01-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_attraction_image_attractionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='created_by',
        ),
    ]
