# Generated by Django 5.0.1 on 2024-01-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_attraction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='exclusions',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='language',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inclusions',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='informationactivities',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='thingstocarry',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
