# Generated by Django 5.0.1 on 2024-01-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_attraction_title_alter_currency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
