# Generated by Django 5.0.1 on 2024-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('ORDERED', 'ORDERED'), ('SUCCESSFUL', 'SUCCESSFUL'), ('CANCELLED', 'CANCELLED'), ('REFUNDED REQUESTED', 'REFUNDED REQUESTED'), ('REFUNDED', 'REFUNDED')], max_length=50, null=True),
        ),
    ]
