# Generated by Django 5.0.1 on 2024-01-29 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_package_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.agent'),
        ),
    ]
