# Generated by Django 5.0.1 on 2024-02-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_refund_amount_transaction_refund_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
    ]
