# Generated by Django 5.0.1 on 2024-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_booking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
