# Generated by Django 5.0.1 on 2024-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_package_images_packageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_published',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
