# Generated by Django 5.0.1 on 2024-02-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activity_activity_uid_package_package_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_day',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_hour',
        ),
    ]
