# Generated by Django 5.0.1 on 2024-02-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_informations_itinerary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='inclusions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations_inclusions', to='api.inclusions'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(choices=[('day', 'Day Night'), ('hour', 'Hours')], default='day', max_length=20, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration Days'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration Hours'),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_night',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration Nights'),
        ),
    ]
