# Generated by Django 5.0.1 on 2024-02-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_informations_inclusions_package_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
    ]
