# Generated by Django 5.0.1 on 2024-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_activity_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='status',
            new_name='stage',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='agent',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
