# Generated by Django 5.0.1 on 2024-02-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_booking_user_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tour_type',
        ),
        migrations.DeleteModel(
            name='TourType',
        ),
    ]
