# Generated by Django 5.0.1 on 2024-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_status_activity_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
