# Generated by Django 5.0.1 on 2024-02-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_package_tour_type_delete_tourtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='refund_id',
            new_name='transaction_uid',
        ),
    ]
