# Generated by Django 5.0.1 on 2024-01-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.BooleanField(),
        ),
    ]
