# Generated by Django 5.0.1 on 2024-02-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_refund_id_transaction_transaction_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='details',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='inclusions',
        ),
        migrations.AlterField(
            model_name='informations',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations_package', to='api.package'),
        ),
        migrations.CreateModel(
            name='ExclusionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('exclusions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_information_exclusion', to='api.exclusions')),
            ],
            options={
                'verbose_name': 'Exclusion Information',
                'verbose_name_plural': 'Exclusion Information',
            },
        ),
        migrations.AddField(
            model_name='informations',
            name='exclusiondetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations_exclusion', to='api.exclusioninformation'),
        ),
        migrations.CreateModel(
            name='InclusionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('inclusions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_information_inclusion', to='api.inclusions')),
            ],
            options={
                'verbose_name': 'Inclusion Information',
                'verbose_name_plural': 'Inclusion Information',
            },
        ),
        migrations.AddField(
            model_name='informations',
            name='inclusiondetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations_inclusion', to='api.inclusioninformation'),
        ),
    ]
