# Generated by Django 5.0.1 on 2024-01-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_baseuser_options_remove_package_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='is_published',
        ),
        migrations.AddField(
            model_name='attraction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='package',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Stage'),
        ),
    ]
