# Generated by Django 5.0.1 on 2024-02-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_informations_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('important_message', models.TextField(blank=True, default='', verbose_name='important Message')),
                ('exclusiondetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations_exclusion', to='api.exclusioninformation')),
                ('inclusiondetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations_inclusion', to='api.inclusioninformation')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations_package', to='api.package')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
            },
        ),
        migrations.DeleteModel(
            name='Informations',
        ),
    ]
