# Generated by Django 5.0.1 on 2024-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_packageinformations_delete_informations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusioninformation',
            old_name='exclusions',
            new_name='exclusion',
        ),
        migrations.RenameField(
            model_name='inclusioninformation',
            old_name='inclusions',
            new_name='inclusion',
        ),
    ]
