# Generated by Django 5.0.1 on 2024-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_attraction_is_published_attraction_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusions',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='exclusions',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='inclusions',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='inclusions',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='exclusions',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Stage'),
        ),
        migrations.AddField(
            model_name='inclusions',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Stage'),
        ),
    ]
