# Generated by Django 5.0.1 on 2024-02-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_exclusions_exclusioninformation_exclusion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='important_message',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='exclusions',
            field=models.ManyToManyField(blank=True, null=True, related_name='itineraries', to='api.exclusions'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='inclusions',
            field=models.ManyToManyField(blank=True, null=True, related_name='itineraries', to='api.inclusions'),
        ),
    ]
