# Generated by Django 5.0.1 on 2024-02-16 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_booking_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount',
            new_name='booking_amount',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='tour_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgentTransactionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=256, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('payment_settlement_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL')], max_length=50, null=True)),
                ('payment_settlement_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_settlement_date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_settlement_agent', to='api.agent')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_transaction_settlement_booking', to='api.booking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_transaction_settlement_package', to='api.package')),
            ],
            options={
                'verbose_name': 'Agent Transaction',
                'verbose_name_plural': 'Agent Transaction',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_person_booking', to='api.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('refund_uid', models.CharField(blank=True, max_length=256, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('refund_status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], max_length=50, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_refund_transaction_booking', to='api.booking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_refund_transaction_package', to='api.package')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_refund_user', to='api.user')),
            ],
            options={
                'verbose_name': 'User Transaction',
                'verbose_name_plural': 'User Transaction',
            },
        ),
    ]
