# Generated by Django 5.0.1 on 2024-02-16 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_amount_booking_booking_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person_booking', to='api.booking'),
        ),
    ]
