# Generated by Django 5.0.1 on 2024-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_activity_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
