# Generated by Django 5.0.1 on 2024-01-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_baseuser_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
