# Generated by Django 5.0.1 on 2024-02-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_agent_managers_alter_baseuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='package',
        ),
        migrations.AddField(
            model_name='activity',
            name='agent',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.state'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='attraction_images/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityimages', to='api.activity')),
            ],
        ),
        migrations.CreateModel(
            name='PackageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageactivity', to='api.package')),
            ],
            options={
                'verbose_name': 'Package Activity',
                'verbose_name_plural': 'Package Activities',
            },
        ),
    ]
