# Generated by Django 5.0.1 on 2024-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_activity_package_activity_agent_activity_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='city_images/'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='country_images/'),
        ),
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='state_images/'),
        ),
    ]
