# Generated by Django 5.0.1 on 2024-02-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_packageinformations_exclusiondetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinformations',
            name='exclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='packageinformations_exclusionclusion', to='api.exclusioninformation'),
        ),
        migrations.AlterField(
            model_name='packageinformations',
            name='inclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='packageinformations_inclusion', to='api.inclusioninformation'),
        ),
    ]
