# Generated by Django 5.0.1 on 2024-02-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_packageinformations_exclusiondetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='amount_percent',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='from_day',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='to_day',
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_booking', to='api.package'),
        ),
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellationpolicy_package', to='api.package'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_state', to='api.state'),
        ),
        migrations.AlterField(
            model_name='exclusioninformation',
            name='exclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusioninformation_exclusion', to='api.exclusions'),
        ),
        migrations.AlterField(
            model_name='faqanswer',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqanswer_package', to='api.package'),
        ),
        migrations.AlterField(
            model_name='faqanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faqanswer_question', to='api.faqquestion'),
        ),
        migrations.AlterField(
            model_name='inclusioninformation',
            name='inclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusioninformation_inclusion', to='api.inclusions'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='exclusions',
            field=models.ManyToManyField(blank=True, related_name='itinerary_exclusions', to='api.exclusions'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='inclusions',
            field=models.ManyToManyField(blank=True, related_name='itinerary_inclusions', to='api.inclusions'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary_day',
            field=models.ManyToManyField(related_name='itinerary_itinerary_day', to='api.itineraryday'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_package', to='api.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_agent', to='api.agent'),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_category', to='api.packagecategory'),
        ),
        migrations.AlterField(
            model_name='package',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_city', to='api.city'),
        ),
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_country', to='api.country'),
        ),
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_state', to='api.state'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageimage_package', to='api.package'),
        ),
        migrations.AlterField(
            model_name='packageinformations',
            name='exclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='packageinformations_exclusiondetails', to='api.exclusioninformation'),
        ),
        migrations.AlterField(
            model_name='packageinformations',
            name='inclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='packageinformations_inclusiondetails', to='api.inclusioninformation'),
        ),
        migrations.AlterField(
            model_name='packageinformations',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageinformations_package', to='api.package'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_package', to='api.package'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_price', to='api.currency'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_country', to='api.country'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourcategory_package', to='api.package'),
        ),
    ]
