# Generated by Django 5.0.1 on 2024-02-19 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_cancellationpolicy_amount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCancellationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('from_day', models.IntegerField(blank=True, null=True)),
                ('to_day', models.IntegerField(blank=True, null=True)),
                ('amount_percent', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellationpolicy_category', to='api.packagecancellationcategory'),
        ),
    ]
