# Generated by Django 5.0.1 on 2024-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_packagecancellationcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='category',
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='cancellationpolicy_category', to='api.packagecancellationcategory'),
        ),
    ]
