# Generated by Django 5.0.1 on 2024-02-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_cancellationpolicy_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQAnswer',
                'verbose_name_plural': 'FAQAnswers',
            },
        ),
        migrations.CreateModel(
            name='PackageFaqQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('category', models.ManyToManyField(blank=True, related_name='package_faq_category', to='api.packagefaqcategory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagefaq_package', to='api.package')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FAQAnswer',
        ),
        migrations.DeleteModel(
            name='FAQQuestion',
        ),
    ]
