# Generated by Django 5.0.1 on 2024-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_packagefaqcategory_packagefaqquestionanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
