# Generated by Django 5.0.1 on 2024-02-19 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_pricing_discount_pricing_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCancellationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('from_day', models.IntegerField(blank=True, null=True)),
                ('to_day', models.IntegerField(blank=True, null=True)),
                ('amount_percent', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Activity Category',
                'verbose_name_plural': 'Activity Category',
            },
        ),
        migrations.CreateModel(
            name='ActivityExclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Activity Exclusions',
                'verbose_name_plural': 'Activity Exclusions',
            },
        ),
        migrations.CreateModel(
            name='ActivityFaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Activity FAQAnswer',
                'verbose_name_plural': 'Activity FAQAnswers',
            },
        ),
        migrations.CreateModel(
            name='ActivityInclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Stage')),
            ],
            options={
                'verbose_name': 'Activity Inclusions',
                'verbose_name_plural': 'Activity Inclusions',
            },
        ),
        migrations.CreateModel(
            name='ActivityItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('day', models.CharField(default='', max_length=255)),
                ('place', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Itinerary Day',
                'verbose_name_plural': 'Itinerary Day',
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activity'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.AddField(
            model_name='activity',
            name='drop_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Drop Point'),
        ),
        migrations.AddField(
            model_name='activity',
            name='drop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Drop Time'),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.CharField(choices=[('day', 'Day Night'), ('hour', 'Hours')], default='day', max_length=20, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration Days'),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration Hours'),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_night',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration Nights'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pickup Point'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tour_class',
            field=models.CharField(choices=[('private', 'Private'), ('conducting', 'Conducting')], default='private', max_length=20, verbose_name='Tour Class'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_agent', to='api.agent'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_city', to='api.city'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_country', to='api.country'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_state', to='api.state'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityimages_activity', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='drop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Drop Time'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='min_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
        migrations.CreateModel(
            name='ActivityCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellationpolicy_activity', to='api.activity')),
                ('category', models.ManyToManyField(blank=True, related_name='activity_cancellationpolicy_category', to='api.activitycancellationcategory')),
            ],
            options={
                'verbose_name': 'Activity Cancellation Policy',
                'verbose_name_plural': 'Activity Cancellation Policies',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_category', to='api.activitycategory'),
        ),
        migrations.CreateModel(
            name='ActivityExclusionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('exclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_exclusioninformation_exclusion', to='api.exclusions')),
            ],
            options={
                'verbose_name': 'Activity Exclusion Information',
                'verbose_name_plural': 'Activity Exclusion Information',
            },
        ),
        migrations.CreateModel(
            name='ActivityFaqQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityfaq_activity', to='api.activity')),
                ('category', models.ManyToManyField(blank=True, related_name='activity_faq_category', to='api.activityfaqcategory')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityInclusionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('inclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_inclusioninformation_inclusion', to='api.inclusions')),
            ],
            options={
                'verbose_name': 'Activity Inclusion Information',
                'verbose_name_plural': 'Activity Inclusion Information',
            },
        ),
        migrations.CreateModel(
            name='ActivityInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('important_message', models.TextField(blank=True, default='', verbose_name='important Message')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_informations_activity', to='api.activity')),
                ('exclusiondetails', models.ManyToManyField(blank=True, related_name='pactivity_informations_exclusiondetails', to='api.activityexclusioninformation')),
                ('inclusiondetails', models.ManyToManyField(blank=True, related_name='activity_informations_inclusiondetails', to='api.activityinclusioninformation')),
            ],
            options={
                'verbose_name': 'Activity Information',
                'verbose_name_plural': 'Activity Informations',
            },
        ),
        migrations.CreateModel(
            name='ActivityItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('overview', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_itinerary_activity', to='api.activity')),
                ('exclusions', models.ManyToManyField(blank=True, related_name='activity_itinerary_exclusions', to='api.activityexclusions')),
                ('inclusions', models.ManyToManyField(blank=True, related_name='activity_itinerary_inclusions', to='api.activityinclusions')),
                ('itinerary_day', models.ManyToManyField(related_name='activity_itinerary_itinerary_day', to='api.activityitineraryday')),
            ],
            options={
                'verbose_name': 'Activity Itinerary',
                'verbose_name_plural': 'Activity Itinerary',
            },
        ),
        migrations.CreateModel(
            name='ActivityPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('group_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('group_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('group_agent_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('pricing_group', models.CharField(choices=[('per_person', 'Per Person'), ('per_group', 'Per Group')], default='per_person', max_length=25)),
                ('adults_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('adults_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('adults_agent_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('child_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('child_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('child_agent_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('infant_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('infant_commission', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('infant_agent_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_pricing_activity', to='api.activity')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_pricing_price', to='api.currency')),
            ],
            options={
                'verbose_name': 'Activity Pricing',
                'verbose_name_plural': 'Activity Pricing',
            },
        ),
        migrations.CreateModel(
            name='ActivityTourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('type', models.CharField(choices=[('through_out_year', 'Through Out Year'), ('seasonal', 'Seasonal'), ('fixed_departure', 'Fixed Departure')], default='through_out_year', max_length=255)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('selected_week_days', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tourcategory_activity', to='api.activity')),
            ],
            options={
                'verbose_name': 'Activity Tour Category',
                'verbose_name_plural': 'Activity Tour Categories',
            },
        ),
    ]
