# Generated by Django 5.0.1 on 2024-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_activitycancellationcategory_activitycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='userreview',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
