# Generated by Django 5.0.1 on 2024-02-20 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_userreview_is_active_userreview_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier'),
        ),
    ]
