# Generated by Django 5.0.1 on 2024-02-20 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_advanceamountpercentagesetting_booking_booking_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimage',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='activityimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityimage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='activityimage',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
