# Generated by Django 5.0.1 on 2024-02-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_activityimage_options_activityimage_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='homepage_display',
            field=models.BooleanField(default=0),
        ),
    ]
