# Generated by Django 5.0.1 on 2024-02-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userreview_homepage_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Tour Type',
                'verbose_name_plural': 'Tour Type',
            },
        ),
        migrations.AddField(
            model_name='advanceamountpercentagesetting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_catgory', to='api.tourtype'),
        ),
    ]
