# Generated by Django 5.0.1 on 2024-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_agenttransactionsettlement_booking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.RemoveField(
            model_name='state',
            name='image',
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='activity/category/cover_image/'),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='thumb_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='activity/category/thumb_images/'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='attraction/cover_image/'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='thumb_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='attraction/thumb_images/'),
        ),
        migrations.AddField(
            model_name='city',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='city/cover_image/'),
        ),
        migrations.AddField(
            model_name='city',
            name='thumb_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='city/thumb_images/'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='package/category/cover_image/'),
        ),
        migrations.AddField(
            model_name='packagecategory',
            name='thumb_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='package/category/thumb_images/'),
        ),
        migrations.AddField(
            model_name='state',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='state/cover_image/'),
        ),
        migrations.AddField(
            model_name='state',
            name='thumb_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='state/thumb_images/'),
        ),
        migrations.AlterField(
            model_name='activityimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='activity_images/'),
        ),
    ]
