# Generated by Django 5.0.1 on 2024-02-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_userreview_agent_userreview_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='agent_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
