# Generated by Django 5.0.1 on 2024-02-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_userreview_agent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransactionsettlement',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_transaction_settlement_activity', to='api.activity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_booking', to='api.activity'),
        ),
        migrations.AddField(
            model_name='userrefundtransaction',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_refund_transaction_activity', to='api.activity'),
        ),
        migrations.AddField(
            model_name='userreview',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_review', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_booking', to='api.package'),
        ),
    ]
