# Generated by Django 5.0.1 on 2024-02-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_agenttransactionsettlement_activity_booking_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_uid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Activity UID'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='activity/category/cover_image/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='thumb_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='activity/category/thumb_images/', verbose_name='Thumb Image'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_uid',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Agent UID'),
        ),
        migrations.AlterField(
            model_name='agenttransactionsettlement',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('PARTIAL PAYMENT', 'PARTIAL PAYMENT'), ('FULL AMOUNT PAYMENT', 'FULL AMOUNT PAYMENT')], max_length=50, null=True, verbose_name='Booking Type'),
        ),
        migrations.AlterField(
            model_name='agenttransactionsettlement',
            name='payment_settlement_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], default='PENDING', max_length=50, null=True, verbose_name='Payment Settlement Status'),
        ),
        migrations.AlterField(
            model_name='agenttransactionsettlement',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Transaction UID'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='attraction/cover_image/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='thumb_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='attraction/thumb_images/', verbose_name='Thumb Image'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Booking UID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('ORDERED', 'ORDERED'), ('SUCCESSFUL', 'SUCCESSFUL'), ('CANCELLED', 'CANCELLED'), ('REFUNDED REQUESTED', 'REFUNDED REQUESTED'), ('REFUNDED', 'REFUNDED'), ('FAILED', 'FAILED')], max_length=50, null=True, verbose_name='Booking Status'),
        ),
        migrations.AlterField(
            model_name='city',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='city/cover_image/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='city',
            name='thumb_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='city/thumb_images/', verbose_name='Thumb Image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_uid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Package UID'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='package/category/cover_image/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='thumb_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='package/category/thumb_images/', verbose_name='Thumb Image'),
        ),
        migrations.AlterField(
            model_name='state',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='state/cover_image/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='state',
            name='thumb_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='state/thumb_images/', verbose_name='Thumb Image'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_uid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Transaction UID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='User UID'),
        ),
        migrations.AlterField(
            model_name='userrefundtransaction',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('REFUNDED', 'REFUNDED')], max_length=50, null=True, verbose_name='Refund Status'),
        ),
        migrations.AlterField(
            model_name='userrefundtransaction',
            name='refund_uid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Refund UID'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='api.user', verbose_name='User'),
        ),
    ]
