# Generated by Django 5.0.1 on 2024-02-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_activity_activity_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusions',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_package', to='api.package'),
        ),
    ]
