# Generated by Django 5.0.1 on 2024-02-26 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_inclusions_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityexclusions',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_activity', to='api.activity'),
        ),
        migrations.AddField(
            model_name='activityinclusions',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_activity', to='api.activity'),
        ),
        migrations.AddField(
            model_name='exclusions',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_package', to='api.package'),
        ),
        migrations.AddField(
            model_name='inclusions',
            name='is_deleted',
            field=models.BooleanField(default=0),
        ),
    ]
