# Generated by Django 5.0.1 on 2024-02-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_activityexclusions_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityexclusions',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='activityinclusions',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='exclusions',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='inclusions',
            name='stage',
        ),
    ]
