# Generated by Django 5.0.1 on 2024-02-28 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_activityexclusions_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityexclusioninformation',
            name='exclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_exclusioninformation_exclusion', to='api.activityexclusions'),
        ),
        migrations.AlterField(
            model_name='activityinclusioninformation',
            name='inclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_inclusioninformation_inclusion', to='api.activityinclusions'),
        ),
    ]
