# Generated by Django 5.0.1 on 2024-02-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_package_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='reject_reason',
        ),
    ]
