# Generated by Django 5.0.1 on 2024-02-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_package_reject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceamountpercentagesetting',
            name='category',
        ),
    ]
