# Generated by Django 5.0.1 on 2024-02-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_advanceamountpercentagesetting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusions',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_activity', to='api.package'),
        ),
        migrations.AddField(
            model_name='inclusions',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_activity', to='api.package'),
        ),
    ]
