# Generated by Django 5.0.1 on 2024-02-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_exclusions_activity_inclusions_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourType',
        ),
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'verbose_name': 'Tour Category', 'verbose_name_plural': 'Tour Category'},
        ),
    ]
