# Generated by Django 5.0.1 on 2024-02-29 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_delete_tourtype_alter_packagecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_category', to='api.packagecategory'),
        ),
        migrations.AlterField(
            model_name='activityexclusioninformation',
            name='exclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_exclusioninformation_exclusion', to='api.exclusions'),
        ),
        migrations.AlterField(
            model_name='activityinclusioninformation',
            name='inclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_inclusioninformation_inclusion', to='api.inclusions'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='exclusions',
            field=models.ManyToManyField(blank=True, related_name='activity_itinerary_exclusions', to='api.exclusions'),
        ),
        migrations.AlterField(
            model_name='activityitinerary',
            name='inclusions',
            field=models.ManyToManyField(blank=True, related_name='activity_itinerary_inclusions', to='api.inclusions'),
        ),
    ]
