# Generated by Django 5.0.1 on 2024-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_activity_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceamountpercentagesetting',
            options={'verbose_name': 'Advance Amount Percentage', 'verbose_name_plural': 'Advance Amount Percentage'},
        ),
        migrations.AlterModelManagers(
            name='agent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='username',
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='unique_username',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
