# Generated by Django 5.0.1 on 2024-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_advanceamountpercentagesetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='unique_username',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Username'),
        ),
    ]
