# Generated by Django 5.0.1 on 2024-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_baseuser_unique_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Agent Name'),
        ),
    ]
