# Generated by Django 5.0.1 on 2024-03-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to='user_review_images/')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='api.userreview')),
            ],
        ),
    ]
