# Generated by Django 5.0.1 on 2024-03-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_agenttransactionsettlement_payment_settlement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
