# Generated by Django 5.0.1 on 2024-03-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_booking_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
    ]
