# Generated by Django 5.0.1 on 2024-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('Change in Travel Plans', 'Change in Travel Plans'), ('Found another Better Deal ', 'Found another Better Deal '), ('Others', 'Others')], max_length=100, null=True, verbose_name='CANCELLATION REASON'),
        ),
    ]
