# Generated by Django 5.0.1 on 2024-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_booking_is_trip_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='drop_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Drop Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
        migrations.AlterField(
            model_name='package',
            name='drop_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Drop Time'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
    ]
