# Generated by Django 5.0.1 on 2024-03-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_activity_drop_time_alter_activity_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='is_viewed',
            field=models.BooleanField(default=0),
        ),
    ]
