# Generated by Django 5.0.1 on 2024-03-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_userreview_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_image', to='api.package'),
        ),
    ]
