# Generated by Django 5.0.1 on 2024-03-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_packageimage_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='is_viewed',
            new_name='is_reviewed',
        ),
    ]
