# Generated by Django 5.0.1 on 2024-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_userreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypricing',
            name='group_agent_amount',
        ),
        migrations.RemoveField(
            model_name='activitypricing',
            name='group_commission',
        ),
        migrations.RemoveField(
            model_name='activitypricing',
            name='group_rate',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='group_agent_amount',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='group_commission',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='group_rate',
        ),
        migrations.AlterField(
            model_name='activitypricing',
            name='pricing_group',
            field=models.CharField(choices=[('per_person', 'Per Person')], default='per_person', max_length=25),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricing_group',
            field=models.CharField(choices=[('per_person', 'Per Person')], default='per_person', max_length=25),
        ),
    ]
