# Generated by Django 5.0.1 on 2024-03-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_remove_activitypricing_group_agent_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='blackout_dates',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
