# Generated by Django 5.0.1 on 2024-03-13 06:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_pricing_blackout_dates_pricing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='blackout_dates',
            field=models.JSONField(blank=True, default=api.models.default_blackout_dates, null=True),
        ),
    ]
