# Generated by Django 5.0.1 on 2024-03-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_pricing_blackout_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_activitya', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_package', to='api.package'),
        ),
    ]
