# Generated by Django 5.0.1 on 2024-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_userreview_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='agent_reply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
