# Generated by Django 5.0.1 on 2024-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_pricing_activity_alter_pricing_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPageInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('clients', models.IntegerField(blank=True, null=True)),
                ('satisfaction', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
