# Generated by Django 5.0.1 on 2024-03-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_coverpageinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is Popular'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is Popular'),
        ),
    ]
