# Generated by Django 5.0.1 on 2024-03-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_exclusions_icon_inclusions_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinformations',
            name='exclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='pactivity_informations_exclusiondetails', to='api.activityexclusioninformation', verbose_name='Exclusion Details'),
        ),
        migrations.AlterField(
            model_name='activityinformations',
            name='inclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='activity_informations_inclusiondetails', to='api.activityinclusioninformation', verbose_name='Inclusion Details'),
        ),
        migrations.AlterField(
            model_name='agenttransactionsettlement',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_transaction_settlement_package', to='api.package'),
        ),
    ]
