# Generated by Django 5.0.1 on 2024-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_activityinformations_exclusiondetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinformations',
            name='exclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='packageinformations_exclusiondetails', to='api.exclusioninformation', verbose_name='Exclusion Details'),
        ),
        migrations.AlterField(
            model_name='packageinformations',
            name='inclusiondetails',
            field=models.ManyToManyField(blank=True, related_name='packageinformations_inclusiondetails', to='api.inclusioninformation', verbose_name='Inclusion Details'),
        ),
    ]
