# Generated by Django 5.0.1 on 2024-03-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_exclusions_icon_remove_inclusions_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverpageinput',
            name='activity_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='coverpageinput',
            name='attraction_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='Attraction'),
        ),
        migrations.AddField(
            model_name='coverpageinput',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='Package'),
        ),
    ]
