# Generated by Django 5.0.1 on 2024-03-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_coverpageinput_activity_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityinformations',
            name='important_message',
        ),
        migrations.AddField(
            model_name='activityitinerary',
            name='important_message',
            field=models.TextField(blank=True, default='', verbose_name='important Message'),
        ),
        migrations.AddField(
            model_name='activityitinerary',
            name='things_to_carry',
            field=models.TextField(blank=True, default='', verbose_name='Things to carry'),
        ),
    ]
