# Generated by Django 5.0.1 on 2024-03-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_remove_activityinformations_important_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_activity', to='api.activity'),
        ),
    ]
