# Generated by Django 5.0.1 on 2024-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_activityimage_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='activity_location', to='api.location', verbose_name='Destinations'),
        ),
        migrations.AlterField(
            model_name='package',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='package_location', to='api.location', verbose_name='Destinations'),
        ),
    ]
