# Generated by Django 5.0.1 on 2024-03-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_alter_city_options_alter_activity_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deal_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('PACKAGE', 'PACKAGE')], default='ACTIVITY', max_length=20, verbose_name='Deal Type'),
        ),
        migrations.AddField(
            model_name='package',
            name='deal_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('PACKAGE', 'PACKAGE')], default='PACKAGE', max_length=20, verbose_name='Deal Type'),
        ),
    ]
