# Generated by Django 5.0.1 on 2024-03-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_activity_deal_type_package_deal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverpageinput',
            name='price_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverpageinput',
            name='price_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
