# Generated by Django 5.0.1 on 2024-03-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_coverpageinput_price_max_coverpageinput_price_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in-progress', 'In-Progress')], default='in-progress', max_length=20, verbose_name='Stage'),
        ),
    ]
