# Generated by Django 5.0.1 on 2024-03-23 04:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_package_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
