# Generated by Django 5.0.1 on 2024-03-23 05:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_alter_itinerary_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='itinerary_day',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Overview'),
        ),
        migrations.DeleteModel(
            name='ItineraryDay',
        ),
    ]
