# Generated by Django 5.0.1 on 2024-03-23 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_activityitinerary_itinerary_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityinclusions',
            name='activity',
        ),
        migrations.AlterField(
            model_name='exclusions',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_activity', to='api.activity'),
        ),
        migrations.AlterField(
            model_name='inclusions',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_activity', to='api.activity'),
        ),
        migrations.DeleteModel(
            name='ActivityExclusions',
        ),
        migrations.DeleteModel(
            name='ActivityInclusions',
        ),
    ]
