# Generated by Django 5.0.1 on 2024-03-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_activity_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='adults_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Adults Commission (%)'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='child_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Adults Commission (%)'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='infant_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Adults Commission (%)'),
        ),
    ]
