# Generated by Django 5.0.1 on 2024-03-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_alter_pricing_adults_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attraction_state', to='api.city', verbose_name='Destinations'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
    ]
