# Generated by Django 5.0.1 on 2024-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_city_is_popular_alter_activity_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecategory',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
    ]
