# Generated by Django 5.0.1 on 2024-03-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_packagecategory_is_popular_state_is_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='thumb_img',
            new_name='thumb_image',
        ),
    ]
