# Generated by Django 5.0.1 on 2024-03-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_booking_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrefundtransaction',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_refund_transaction_package', to='api.package'),
        ),
    ]
