# Generated by Django 5.0.1 on 2024-03-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_alter_userrefundtransaction_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in-progress', 'In-Progress')], default='in-progress', max_length=20, verbose_name='Stage'),
        ),
    ]
