# Generated by Django 5.0.1 on 2024-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_alter_activity_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverpageinput',
            name='price_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
