# Generated by Django 5.0.1 on 2024-03-27 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_alter_coverpageinput_price_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_enquiry_activity', to='api.activity')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_enquiry_package', to='api.package')),
            ],
            options={
                'verbose_name': 'Send Enquiry',
                'verbose_name_plural': 'Send Enquiry',
            },
        ),
    ]
