# Generated by Django 5.0.1 on 2024-03-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_sendenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendenquiry',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
