# Generated by Django 5.0.1 on 2024-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_alter_sendenquiry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverpageinput',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='Product'),
        ),
    ]
