# Generated by Django 5.0.1 on 2024-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_coverpageinput_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company ID'),
        ),
        migrations.AddField(
            model_name='agent',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='agent',
            name='company_site',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Site'),
        ),
        migrations.AddField(
            model_name='agent',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='coverpageinput',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/', verbose_name='All Deals'),
        ),
    ]
