# Generated by Django 5.0.1 on 2024-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_agent_company_id_agent_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitableFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Suitable For',
                'verbose_name_plural': 'Suitable For',
            },
        ),
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='package',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='tour_activity',
            field=models.ManyToManyField(blank=True, related_name='activity_tour_activity', to='api.packagecategory', verbose_name='Activities'),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_activity',
            field=models.ManyToManyField(blank=True, related_name='package_tour_activity', to='api.packagecategory', verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='company_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Registration Number'),
        ),
        migrations.AddField(
            model_name='activity',
            name='suitable_for',
            field=models.ManyToManyField(blank=True, related_name='activity_suitablefor', to='api.suitablefor', verbose_name='Suitable For'),
        ),
        migrations.AddField(
            model_name='package',
            name='suitable_for',
            field=models.ManyToManyField(blank=True, related_name='package_suitablefor', to='api.suitablefor', verbose_name='Suitable For'),
        ),
    ]
