# Generated by Django 5.0.1 on 2024-05-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_suitablefor_alter_packagecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='tour_activity',
            new_name='activities',
        ),
    ]
