# Generated by Django 5.0.1 on 2024-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_rename_tour_activity_activity_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='tour_activity',
            new_name='activities',
        ),
    ]
