# Generated by Django 5.0.1 on 2024-05-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_rename_tour_activity_package_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField(verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=255, verbose_name='IFSC Code')),
                ('cancelled_cheque', models.ImageField(blank=True, default=None, null=True, upload_to='cancelled_cheques/', verbose_name='Cancelled Cheque')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='api.agent')),
            ],
            options={
                'verbose_name': 'Agent Bank Details',
                'verbose_name_plural': 'Agent Bank Details',
            },
        ),
    ]
