# Generated by Django 5.0.1 on 2024-05-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_agentbankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='account_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Bank Account Verification'),
        ),
    ]
