# Generated by Django 5.0.1 on 2024-05-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_agent_account_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbankdetails',
            name='account_number',
            field=models.CharField(max_length=255, verbose_name='Account Number'),
        ),
    ]
