# Generated by Django 5.0.1 on 2024-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_alter_agentbankdetails_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Recommended'),
        ),
        migrations.AddField(
            model_name='package',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Recommended'),
        ),
    ]
