# Generated by Django 5.0.1 on 2024-05-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_blogcategory_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blog_categories', to='api.blogcategory'),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Blog Image')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blogs')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='blogs_image', to='api.blogimage'),
        ),
    ]
