# Generated by Django 5.0.1 on 2024-05-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_blogs_categories_blogimage_blogs_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='blog',
        ),
    ]
