# Generated by Django 5.0.1 on 2024-05-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_remove_blogimage_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='images',
        ),
    ]
