# Generated by Django 5.0.1 on 2024-05-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_remove_blogs_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs_image', to='api.blogs'),
        ),
    ]
