# Generated by Django 5.0.1 on 2024-05-15 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_alter_blogs_options_favoriteproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_country', to='api.country'),
        ),
    ]
