# Generated by Django 5.0.1 on 2024-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_historicalpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpricing',
            name='changed_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicalpricing',
            name='is_changed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
