# Generated by Django 5.0.1 on 2024-05-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_booking_adults_rate_booking_child_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Adults Commission (%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Child Commission (%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='infant_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Infant Commission (%)'),
        ),
    ]
