# Generated by Django 5.0.1 on 2024-05-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_booking_adults_commission_booking_child_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbankdetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
    ]
