# Generated by Django 5.0.1 on 2024-05-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_agentbankdetails_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='company_site',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Website'),
        ),
    ]
