# Generated by Django 5.0.1 on 2024-05-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_alter_agent_company_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
