# Generated by Django 5.0.1 on 2024-05-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_activity_min_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('day', models.CharField(default='', max_length=255)),
                ('place', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Itinerary Day',
                'verbose_name_plural': 'Itinerary Day',
            },
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='description',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_day',
            field=models.ManyToManyField(blank=True, related_name='itinerary_day', to='api.itineraryday'),
        ),
    ]
