# Generated by Django 5.0.1 on 2024-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_itineraryday_remove_itinerary_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_class',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Mid Range', 'Mid Range'), ('Luxury', 'Luxury'), ('Luxury Plus', 'Luxury Plus')], default='Budget', max_length=20, verbose_name='Package Class'),
        ),
        migrations.AddField(
            model_name='state',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
