# Generated by Django 5.0.1 on 2024-05-23 15:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_itineraryday_remove_itinerary_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('place', models.CharField(blank=True, max_length=256, null=True, verbose_name='Place')),
                ('hotel_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Hotel Name')),
            ],
            options={
                'verbose_name': 'Stay Details',
                'verbose_name_plural': 'Stay Details',
            },
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='important_message',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='inclusions',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='things_to_carry',
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='InclusionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('inclusion_details', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Inclusion Details')),
                ('exclusion_details', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Exclusion Details')),
                ('inclusions', models.ManyToManyField(blank=True, related_name='itinerary_inclusions', to='api.inclusions')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_exclusion_package', to='api.package')),
            ],
            options={
                'verbose_name': 'Inclusions And Exclusions',
                'verbose_name_plural': 'Inclusions And Exclusions',
            },
        ),
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('things_to_carry', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Things to carry')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations_package', to='api.package')),
                ('stay_details', models.ManyToManyField(blank=True, related_name='informations_stay_details', to='api.staydetails')),
            ],
            options={
                'verbose_name': 'Stay Details',
                'verbose_name_plural': 'Stay Details',
            },
        ),
    ]
