# Generated by Django 5.0.1 on 2024-05-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_staydetails_remove_itinerary_exclusions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'verbose_name': 'Information', 'verbose_name_plural': 'Informations'},
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='api.country'),
        ),
    ]
