# Generated by Django 5.0.1 on 2024-05-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_alter_informations_options_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrefundtransaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transaction Date'),
        ),
    ]
