# Generated by Django 5.0.1 on 2024-05-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_userrefundtransaction_transaction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Super Admin', 'verbose_name_plural': 'Super Admin'},
        ),
    ]
