# Generated by Django 5.0.1 on 2024-06-21 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('unique_username', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Username')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('is_staff', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Super Admin',
                'verbose_name_plural': 'Super Admin',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agent_uid', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Agent UID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/agent/')),
                ('username', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('agent_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Agent Name')),
                ('company_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Registration Number')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name')),
                ('company_site', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Website')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Stage')),
                ('account_verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Bank Account Verification')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_uid', models.CharField(blank=True, max_length=256, null=True, verbose_name='User UID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/user/')),
                ('username', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='AgentBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=255, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(max_length=255, verbose_name='IFSC Code')),
                ('cancelled_cheque', models.ImageField(blank=True, default=None, null=True, upload_to='cancelled_cheques/', verbose_name='Cancelled Cheque')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounts.agent')),
            ],
            options={
                'verbose_name': 'Agent Bank Details',
                'verbose_name_plural': 'Agent Bank Details',
            },
        ),
    ]
