
BOOKING_TYPE =(
            ("PARTIAL PAYMENT", "PARTIAL PAYMENT"),
            ("FULL AMOUNT PAYMENT", "FULL AMOUNT PAYMENT"), 
            )

DEALTYPE_CHOICE = [
    ('ACTIVITY', 'ACTIVITY'),
    ('PACKAGE', 'PACKAGE'),
]